### ISSUE TITLE
hardware_config.json

### ISSUE THREAD

**Issue by taospartan** [LCAV/easy-dsp#12]
Do you have an example of a hardware_config.json file that I can use to define my own array? 

Many thanks

Tao

**Comment by fakufaku** [comment]
Sure, here is what I use:
```
{
  "led_ring_address": "/dev/cu.usbmodem1421",
  "sampling_frequency": 48000,
  "array_type": "circular"
}
```
The file is read in the script that does the processing. In our case, the array type is simply indicated by a string. The actual positions of the microphones were then defined in the script itself. The `led_ring_address` is the serial interface of an LED ring that was used during a demo. The `sampling_frequency` should be fixed to what your array needs. What kind of array are you using ? Iin our case, we had two different hardware which is why we needed the local configuration file. If you are only using one array you can also ignore the `hardware_config.json` file and simply define everything in the script.

**Comment by taospartan** [comment]
Many thanks:) I have 2 arrays I’m going to try:

Minidsp uma16
Respeaker mic array v2

I’m assuming I just pass cords of the mics from the centre of the array?

Cheers

Tao

**Comment by fakufaku** [comment]
Yes, coordinates of the mics from the center of the array should be fine. All the TDOA based methods are not sensitive to the placement of the origin since they ultimately only consider the differences of coordinates.

Edit: Make sure to double check the matching of channels to coordinates as it is a nasty source of error quite difficult to debug :)

**Comment by taospartan** [comment]
Will do:)
