### ISSUE TITLE
Let the microphone array advertise the available stream configurations

### ISSUE THREAD

**Issue by fakufaku** [LCAV/easy-dsp#4]
The wsconfig demon could send a list of available rates and options upon connection. This would let the browser display correctly the available rates and number of channels.

**Comment by ebezzam** [comment]
@fakufaku I've solved this issue another way. The main daemon uses the socket with WSAudio (as there is no communication from Main Daemon to WSConfig) to advertise the available stream configurations (at the moment supported number of channels and rates). I've added another "magic header" to differentiate between the other messages to WSAudio. WSAudio then sends the supported configurations to the client via `libwebsock` in a similar way the current configuration is sent. I've also updated `js/main.js' and 'index.html' so that only the supported number of channels and rates can be selected from the browser display. 

Still to do:
1. Send other supported steam configuration such as buffer size.
2. Some sort of check in `browserinterface.change_config()` so that only valid configurations can be sent to the WSConfig daemon.
3. Align the dropdown entries in the browser display under "Change configuration".

Let me know if you have any suggestions or improvements for this solution!

**Comment by fakufaku** [comment]
Hi @ebezzam that sounds like a great start and is good enough for now! Actually, I think we should merge all three daemons into a single one. Because all of them are multithreaded in the first place, it does not make much sense to keep them separate.
In addition, it would bring several advantages. They would all share memory space and we wouldn't need to use the local sockets for communication anymore. This would also solve the problem of sending the config between daemons, as well as the data. What is now the main daemon would push the data in a queue which would be sent directly using libwebsocks. All threads would have access to available rates and other information. Things would be much simpler in general.
@NTag Do you agree with this solution ?

**Comment by NTag** [comment]
I just wonder if this will not reduce the modularity. How will that work if somebody wants to port the program to another architecture? The initial idea was that he would only need to change the main daemon. Even using another language for it.

But, if into this merged program, the three parts are keep separated (so the main part could be easily changed without having the modify the WSAudio and WSConfig parts), I think it could work.

**Comment by fakufaku** [comment]
You're correct about modularity. I think with regards to that, the best solution would have to define a layer abstracting the audio access. Then only that could be modified for different architectures (ALSA, pyramicio, etc) using some compile time options.

**Comment by fakufaku** [comment]
Actually, it wouldn't hurt much in terms of modularity. The three files are almost unchanged. What will change is that all the threads will be started from the same `main`. The Makefile will change a little bit, but not so much.
A queue will be needed to replace the TCP links, but that won't be such an issue. There will still be some outstanding synchronization issues to take care of between the threads, so we'll have to be careful.
